# Generated by Django 4.0.3 on 2022-04-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=12)),
                ('Title', models.CharField(max_length=122)),
                ('Start_Time', models.CharField(max_length=122)),
                ('End_Time', models.CharField(max_length=122)),
                ('Date', models.CharField(max_length=122)),
                ('Description', models.CharField(max_length=122)),
                ('Modified_Date', models.CharField(max_length=122)),
            ],
        ),
    ]
